version: '2'
services:
  mysql:
    image: mysql
    hostname: mysql
    container_name: mysql
    restart: always
    network_mode: host
    mem_limit: 1024m
    volumes:
      - mysql-data:/var/lib/mysql-data
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: testdb
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    container_name: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq-data
    restart: always
    network_mode: host
    mem_limit: 1024m
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
    restart: always
    network_mode: host
    volumes:
      - mongo-data:/var/lib/mongo-data
    command: mongod --storageEngine=wiredTiger --wiredTigerCacheSizeGB=1 --notablescan --journalCommitInterval=300 --directoryperdb
  redis:
    image: redis
    hostname: redis
    container_name: redis
    restart: always
    network_mode: host
    mem_limit: 512m
    volumes:
      - redis-data:/varlib/redis-data
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    network_mode: host
    mem_limit: 1024m
    environment:
      POSTGRES_PASSWORD: sa
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    volumes:
      - postgres-data:/varlib/postgres-data

volumes:
  mysql-data:
    external: true
  rabbitmq-data:
    external: true
  mongo-data:
    external: true
  redis-data:
    external: true
  postgres-data:
    external: true

